services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    network:
      - inventory_net

  api:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "${API_PORT}:5050"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    network:
      - inventory_net

  web:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "${WEB_PORT}:80"
    environment:
      API_BASE_URL: ${API_BASE_URL}
    network:
      - inventory_net

volumes:
  db_data:

networks:
  inventory_net
    driver:bridge
